{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Orders\",\"USD_Rates\",\"Customers\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.118.621.0 (23.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "d146a5b9-f2a4-445a-b6be-839bd1383ebc",
        "fromColumn": "DeliveryDate",
        "fromTable": "Orders",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7f33ed60-64ca-4446-b3a4-c14b7e485dab"
      },
      {
        "name": "0f99c011-a888-49e6-a002-d8fad3129560",
        "fromColumn": "Currency",
        "fromTable": "Orders",
        "toColumn": "Currency",
        "toTable": "USD_Rates"
      },
      {
        "name": "00d443bb-def3-43c7-a77f-462c7d98b219",
        "fromColumn": "CustomerID",
        "fromTable": "Orders",
        "toColumn": "CustomerID",
        "toTable": "Customers"
      },
      {
        "name": "297e2ad0-a059-4774-ad07-eea9496b4f68",
        "fromColumn": "Order Date",
        "fromTable": "Dates",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_dd0c98ea-2ecc-4f0a-afc2-7ffacade29c6"
      },
      {
        "name": "8b5df3e9-b1e0-4c21-8ac3-8885d2b0857c",
        "fromColumn": "Order Date",
        "fromTable": "Orders",
        "toColumn": "Order Date",
        "toTable": "Dates"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Customers",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "845919f1-5adc-4795-9f5d-fd6cfaaaac1c",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9f9deedd-7d4f-46e0-859d-6c8d18aaf359",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd7dea2a-b9cc-4727-b0f1-04669c36c24f",
            "sourceColumn": "CustomerName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ff3a9f59-016b-4cb2-879b-0d784e2ecfe2",
        "partitions": [
          {
            "name": "Customers-5b3f71ea-f487-4f5a-b05a-9a5b4dc573d4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"\\\\aspen.local\\DFSUsers$\\LDN\\RojeJ\\My Documents\\DataAnalysis\\Power BI Training\\Sample Data.xlsx\"), null, true),",
                "    Customers_Table = Source{[Item=\"Customers\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Customers_Table,{{\"CustomerID\", Int64.Type}, {\"CustomerName\", type text}, {\"City\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_edfc55da-5961-4084-9e9e-d1f03c4b613e",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2119f589-7a46-481f-8207-7be393ff25b4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "831a90e8-7ef7-4ab4-a7e6-918d24fdf78a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cfa4269a-65f3-4689-a4d7-880ac70a3c11",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6a13f982-8f92-4109-9b5c-6f84504c1ece",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9fe265d6-b9bb-41c4-b07b-80273bd0ec14",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7631600c-1753-4c70-ace1-e743124fd985",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1f5f1e3a-a23b-404d-ae8b-cbae5efc1e1d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "20f51866-d185-4fc2-9e74-1fb0a714a6a9",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "0040ba7a-d3e7-432c-8895-1fa59d177d6d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b23d9c0c-4721-4ebc-9638-37416e856b99",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9abc0ba4-47da-447b-b81e-f9e0815e6763",
                "ordinal": 3
              }
            ],
            "lineageTag": "847ca597-e3e1-47e5-8fd5-c2deabbe5673"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "4ac3740b-7394-4af2-aa10-7872d27b93b0",
        "partitions": [
          {
            "name": "DateTableTemplate_edfc55da-5961-4084-9e9e-d1f03c4b613e-cec53482-f8aa-4f5d-9aa8-72fdb6cc66d2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dates",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4a6f563019ed4cc8be79622f317dd444"
          }
        ],
        "columns": [
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "203c25ee-2681-4a67-a330-b9d9b2f6824b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_dd0c98ea-2ecc-4f0a-afc2-7ffacade29c6"
                },
                "isDefault": true,
                "relationship": "297e2ad0-a059-4774-ad07-eea9496b4f68"
              }
            ]
          }
        ],
        "lineageTag": "8f12614c-454b-49ef-a21a-664a08d622d5",
        "partitions": [
          {
            "name": "Dates-0554fbe9-88ac-4c74-96c9-a674d3e9ff7d",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(DATE(2023,1,1), DATE(2023,1,31) )",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_7f33ed60-64ca-4446-b3a4-c14b7e485dab",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "de133c8f-9b4b-48b0-a986-3d572052c3b7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c019abc4-0177-44aa-9fe9-1d75bb2fbb53",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "173b4412-d99f-4903-9bc4-7ecbc9c28fa5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bb10d765-6bae-4f18-95d0-a6890706a46b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2458d16e-bd8b-472b-9c81-0ba0bec4cc6e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3ecf6942-19be-4815-a39e-f3caba16b15b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "72fd92db-9be4-40b3-a937-ea3eab755ef8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0b19772f-f356-4541-b55a-aa13d0bc164a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2bb08c2f-f361-4bf7-9109-45db09aa0ee3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "455625b1-55f0-43d9-95a6-1b954465df79",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e68ffc37-0cc9-4b67-a5cc-b17525117f2d",
                "ordinal": 3
              }
            ],
            "lineageTag": "2787d595-d9f0-478c-95c5-4240a6ff7c42"
          }
        ],
        "isHidden": true,
        "lineageTag": "0d8a4a9c-4a4c-4d08-b96e-9bca9fb0a29f",
        "partitions": [
          {
            "name": "LocalDateTable_7f33ed60-64ca-4446-b3a4-c14b7e485dab-48a58e4f-c78d-4f67-9d5c-786dda8b180d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Orders'[DeliveryDate])), 1, 1), Date(Year(MAX('Orders'[DeliveryDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_dd0c98ea-2ecc-4f0a-afc2-7ffacade29c6",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7ba5f362-3e54-47eb-96e2-ae53268a1826",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "45299cc3-0cfb-4f8c-85d1-faef3c7eda56",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5e263297-8ad6-4f81-86bc-2f0bdb0d25d0",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2836f5bb-5980-41c5-9158-ebe90babca95",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "dc10da48-1141-435f-a090-24d14d6bf98c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "831e2337-7bca-475d-a6a9-bc7b3a460617",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "08d19876-b958-4ec5-a2c9-55f660671d41",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "601c1dc2-4f9d-4cde-9782-534332db06ba",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "10b682f8-74a2-465a-bd95-a8454a2473f0",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e3faa999-9268-45b6-a358-65daeacfc47c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "917ff85c-2029-432d-82e0-848c3f652a9b",
                "ordinal": 3
              }
            ],
            "lineageTag": "6a75552c-c838-42a4-b040-88d8bef97402"
          }
        ],
        "isHidden": true,
        "lineageTag": "6d7160d8-610a-4fa5-9c80-a9c767d3dabb",
        "partitions": [
          {
            "name": "LocalDateTable_dd0c98ea-2ecc-4f0a-afc2-7ffacade29c6-d91a4c66-c8cc-4bf2-9b2b-e16b30c9addc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dates'[Order Date])), 1, 1), Date(Year(MAX('Dates'[Order Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Orders",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "271e8f26-4f5d-4035-9b18-a97f7b7825ec",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "67cf7577-75a1-4589-8d31-d6825f7eb872",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "DeliveryDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "27fe0f92-6fa7-47ca-8c41-5e3b8a0e7ad4",
            "sourceColumn": "DeliveryDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7f33ed60-64ca-4446-b3a4-c14b7e485dab"
                },
                "isDefault": true,
                "relationship": "d146a5b9-f2a4-445a-b6be-839bd1383ebc"
              }
            ]
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "35014d30-5b7e-48d9-a1a3-893d5127ed7a",
            "sourceColumn": "Order Date",
            "summarizeBy": "none"
          },
          {
            "name": "OrderPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "Orders[UnitPrice] * Orders[Units]",
            "isDataTypeInferred": true,
            "lineageTag": "fdbb64d1-0986-4134-a777-ee1528128dfc",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6fe67f9a-11b9-4a1a-88c1-94fad4f6779a",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "Units",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e95d4393-a713-4258-b14a-42751570eb1f",
            "sourceColumn": "Units",
            "summarizeBy": "average"
          }
        ],
        "lineageTag": "5909ed3c-7bcf-4815-a747-17fb0fd89f7e",
        "measures": [
          {
            "name": "_OrderPrice",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUMX(Orders, Orders[UnitPrice]*Orders[Units])",
            "lineageTag": "0790d572-b077-48ec-9f80-87e42e4aaea5"
          },
          {
            "name": "_OrderPriceUSD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUMX(Orders, Orders[UnitPrice]*Orders[Units]/RELATED(USD_Rates[Rate]) )",
            "lineageTag": "2efa610e-dca1-4683-a24a-38d7ee69ec96"
          },
          {
            "name": "_OrderPriceUSD running total in Date",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "\t[_OrderPriceUSD],",
              "\tFILTER(",
              "\t\tALLSELECTED('Dates'[Order Date]),",
              "\t\tISONORAFTER('Dates'[Order Date], MAX('Dates'[Order Date]), DESC)",
              "\t)",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "RunningTotal",
                  "version": 0
                }
              }
            ],
            "lineageTag": "70f4f590-2521-41ef-a894-01d58c6a409b"
          }
        ],
        "partitions": [
          {
            "name": "Orders-badf5294-b592-489a-8f79-4602cbdce1a8",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"\\\\aspen.local\\DFSUsers$\\LDN\\RojeJ\\My Documents\\DataAnalysis\\Power BI Training\\Sample Data.xlsx\"), null, true),",
                "    Orders_Table = Source{[Item=\"Orders\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Orders_Table,{{\"Units\", Int64.Type}, {\"UnitPrice\", type number}, {\"Currency\", type text}, {\"OrderDate\", type date}, {\"DeliveryDate\", type date}, {\"CustomerID\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"OrderDate\", \"Order Date\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "USD_Rates",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "639d7e72-b934-4959-b57f-67540ebc4437",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          },
          {
            "name": "Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "150a8fcf-639b-46e1-b82c-a49a31a70ffd",
            "sourceColumn": "Rate",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f699cb96-c9c1-4158-a083-ed59a0882ed4",
        "partitions": [
          {
            "name": "USD_Rates-8e7a3521-2cc1-467f-8158-b1a3dee3fc4b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"\\\\aspen.local\\DFSUsers$\\LDN\\RojeJ\\My Documents\\DataAnalysis\\Power BI Training\\Sample Data.xlsx\"), null, true),",
                "    USD_Rates_Table = Source{[Item=\"USD_Rates\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(USD_Rates_Table,{{\"Currency\", type text}, {\"Rate\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}