{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"fixtures\",\"lineups\",\"player_stats\",\"players\",\"teams\",\"events\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.118.621.0 (23.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "1f3aa5e6-04bd-4da9-82e3-a232fd27cb0d",
        "fromColumn": "fixture_date",
        "fromTable": "fixtures",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b4dcedc9-394f-4752-b191-86fb0e9f9168"
      },
      {
        "name": "b3394e09-0de3-47e6-927c-239202816284",
        "fromColumn": "birth_date",
        "fromTable": "players",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a861fe3f-b93f-449f-ab4f-86203259d8f4"
      },
      {
        "name": "11cc932a-4779-4572-b574-3dfb7ca2c19d",
        "fromColumn": "player_id",
        "fromTable": "events",
        "toColumn": "player_id",
        "toTable": "players"
      },
      {
        "name": "c97e37e7-1407-4fa6-94ff-5b520875621a",
        "fromColumn": "team_id",
        "fromTable": "events",
        "toColumn": "team_id",
        "toTable": "teams"
      },
      {
        "name": "eab8935e-81ed-4442-b985-635826b2cd5a",
        "fromColumn": "fixture_id",
        "fromTable": "events",
        "toColumn": "fixture_id",
        "toTable": "fixtures"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "DateTableTemplate_9e357d79-b58e-4435-b590-9090ddf4634c",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "001666da-59d3-459c-a096-0380f9f43fbe",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "71fe6ccb-978b-475a-94bb-64d66481c925",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "66bee9ff-8365-46b6-b68c-e31501614632",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7997ef1d-f3d4-46e8-b7dc-bb95a042d859",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "411fe5a9-e154-4eb6-9586-70d3ef8a4d60",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "681ae95f-d93d-412b-96b6-5b4d5815df2e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f4da3400-84b2-4219-bdb4-7102de8afe8c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "517e1f9e-2f21-4c8d-a437-d2f212613524",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8abf8a6c-469f-41cc-aedf-71980de8e13c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "28bccd30-d0ac-4f01-a987-a806aef0e464",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "957b80df-1b07-40d5-8b82-fab4408572a3",
                "ordinal": 3
              }
            ],
            "lineageTag": "4a139c1a-a2f5-41e7-9962-1419bc5b9072"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "dbac5bba-2bed-45c6-aa44-1d1d039abac1",
        "partitions": [
          {
            "name": "DateTableTemplate_9e357d79-b58e-4435-b590-9090ddf4634c-a8b2f685-07eb-44f1-bc5f-0ce0bdcc8742",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a861fe3f-b93f-449f-ab4f-86203259d8f4",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "845793e9-0a69-4aaa-b2f0-188397bebcc6",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "43001fa0-25ae-4b87-a325-7cc8a02d629a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c41eb330-7cc4-4efe-aea5-27336f90c2b6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3e45c01f-d0a2-446e-87a4-057a5dd00aa8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b88e292d-b34c-49c8-8882-411d595efe19",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "29466357-b52d-496a-98f7-368e3fb0f168",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "969418bc-485c-40e4-9558-14503e16ba63",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "cda61d28-db11-41a1-9a3e-e5b4f9419989",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6d3b3096-445b-4d60-a04f-7b85778c0e66",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4fd1fbd5-09a1-44a5-81bb-1d4512ba5f3b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0458d2b9-f6ad-4300-9c73-0c1c23214082",
                "ordinal": 3
              }
            ],
            "lineageTag": "e559220e-6472-42c1-b33e-e816fa8777a8"
          }
        ],
        "isHidden": true,
        "lineageTag": "bfe3f541-851b-4eaa-b512-8e937be95123",
        "partitions": [
          {
            "name": "LocalDateTable_a861fe3f-b93f-449f-ab4f-86203259d8f4-88192426-ed69-4f6c-a862-a7799dcab164",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('players'[birth_date])), 1, 1), Date(Year(MAX('players'[birth_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_b4dcedc9-394f-4752-b191-86fb0e9f9168",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8f6cf690-fbd1-4eeb-b307-45b73b1e2f49",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "501456c7-d760-48c2-80ec-864b24e2ae6c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e1a86b04-5c61-4c57-892e-93f2f09cebbf",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "06b3a043-fffb-49dc-bf1e-09fbd26f0ee1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b0c69ec6-9d78-496b-8550-d1be6fd46a35",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "730257d1-3787-40cc-905b-ed01dacb2b35",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d2153d9f-4735-4c16-a32b-2f55980d9b4b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "76b29404-e525-4f73-91d7-fa5d864f8160",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4cb175ca-8cbb-444c-87fa-c7d85b81a930",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "99ebe185-46c5-4eda-834f-4396425cfe47",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "cc279050-64a9-4bd7-8d10-11fb4f28d627",
                "ordinal": 3
              }
            ],
            "lineageTag": "816fcb1b-a3d0-42da-9925-976283c27b07"
          }
        ],
        "isHidden": true,
        "lineageTag": "5a0be8d7-88c2-4cf5-83dc-e7974c37f5f8",
        "partitions": [
          {
            "name": "LocalDateTable_b4dcedc9-394f-4752-b191-86fb0e9f9168-c282cfac-6573-484e-807c-0ca7d7b15055",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fixtures'[fixture_date])), 1, 1), Date(Year(MAX('fixtures'[fixture_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "events",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "assisting_player_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "36112538-e564-488a-96a6-5b0009837992",
            "sourceColumn": "assisting_player_id",
            "summarizeBy": "sum"
          },
          {
            "name": "comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "247b51fd-e5a4-44d6-9733-06aa9f343464",
            "sourceColumn": "comments",
            "summarizeBy": "none"
          },
          {
            "name": "detail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa89729f-29cb-4946-bf61-7f02bd75a089",
            "sourceColumn": "detail",
            "summarizeBy": "none"
          },
          {
            "name": "fixture_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "765f0072-1293-497d-9c53-79ce30e75ec7",
            "sourceColumn": "fixture_id",
            "summarizeBy": "none"
          },
          {
            "name": "player_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d9ff0859-4b95-4b2b-8cce-6c3f4e5a8e82",
            "sourceColumn": "player_id",
            "summarizeBy": "none"
          },
          {
            "name": "team_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "db97e291-462e-46da-889b-ddf5b3a57d81",
            "sourceColumn": "team_id",
            "summarizeBy": "none"
          },
          {
            "name": "type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d4b5286-44fd-4b53-bbf0-fb8e8d5ca7eb",
            "sourceColumn": "type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5cbf2095-2831-4bf5-96b5-65288e52bff5",
        "measures": [
          {
            "name": "Goals",
            "expression": [
              "",
              "VAR goaltable = FILTER(events, events[type]=\"Goal\")",
              "RETURN COUNTROWS(goaltable)"
            ],
            "formatString": "0",
            "lineageTag": "77c8480c-6639-4201-8497-ad6214e5c1da"
          }
        ],
        "partitions": [
          {
            "name": "events-35dbb4a7-72c8-44e1-8bbd-d67871ce68e9",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(\"adb-6574875493875899.19.azuredatabricks.net\", \"sql/protocolv1/o/6574875493875899/0607-092353-qlk3ujuf\", [Catalog=null, Database=\"silver\", EnableAutomaticProxyDiscovery=null]),",
                "    teams_silver_hive_metastore = Source{[Item=\"events\",Schema=\"silver\",Catalog=\"hive_metastore\"]}[Data]",
                "in",
                "    teams_silver_hive_metastore"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fixtures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Fixture name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE( CONCATENATE(fixtures[home_team], \" - \"), fixtures[away_team])",
            "isDataTypeInferred": true,
            "lineageTag": "984ef8c2-dd45-46af-b9d5-deddb34c8465",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "away_team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c79d877e-4051-49ea-ac57-762ad9873429",
            "sourceColumn": "away_team",
            "summarizeBy": "none"
          },
          {
            "name": "away_team_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bd385f63-5a82-48b3-97a8-920c3fa59462",
            "sourceColumn": "away_team_id",
            "summarizeBy": "sum"
          },
          {
            "name": "away_team_logo_url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "5b9e7e91-8734-4db7-8b35-38a9f998f2ac",
            "sourceColumn": "away_team_logo_url",
            "summarizeBy": "none"
          },
          {
            "name": "fixture_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "dcca0626-e957-4238-a32b-d00d94d70ec9",
            "sourceColumn": "fixture_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b4dcedc9-394f-4752-b191-86fb0e9f9168"
                },
                "isDefault": true,
                "relationship": "1f3aa5e6-04bd-4da9-82e3-a232fd27cb0d"
              }
            ]
          },
          {
            "name": "fixture_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "702be957-052d-4356-ac02-d442da52fb00",
            "sourceColumn": "fixture_id",
            "summarizeBy": "none"
          },
          {
            "name": "home_team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e968b544-1db6-433d-a108-a59d2cc3a27d",
            "sourceColumn": "home_team",
            "summarizeBy": "none"
          },
          {
            "name": "home_team_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75b638f3-6085-4263-ab36-3e9344e18f11",
            "sourceColumn": "home_team_id",
            "summarizeBy": "sum"
          },
          {
            "name": "home_team_logo_url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "5176cda3-9c25-4d20-8709-0b5712c875ac",
            "sourceColumn": "home_team_logo_url",
            "summarizeBy": "none"
          },
          {
            "name": "league_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "330576c8-d351-431c-93c9-df29e98128f1",
            "sourceColumn": "league_id",
            "summarizeBy": "sum"
          },
          {
            "name": "season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05e14a1d-a8bd-4140-baac-92ce4a2b5bd7",
            "sourceColumn": "season",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0c07be54-a50a-4faf-b376-24f71c10a2d8",
        "partitions": [
          {
            "name": "fixtures-305dfe3c-38ad-431e-ac40-21adcfdc8398",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(\"adb-6574875493875899.19.azuredatabricks.net\", \"sql/protocolv1/o/6574875493875899/0607-092353-qlk3ujuf\", [Catalog=null, Database=\"silver\", EnableAutomaticProxyDiscovery=null]),",
                "    fixtures_silver_hive_metastore = Source{[Item=\"fixtures\",Schema=\"silver\",Catalog=\"hive_metastore\"]}[Data],",
                "    #\"Merged Queries\" = Table.NestedJoin(fixtures_silver_hive_metastore, {\"home_team_id\"}, teams, {\"team_id\"}, \"teams\", JoinKind.LeftOuter),",
                "    #\"Expanded teams\" = Table.ExpandTableColumn(#\"Merged Queries\", \"teams\", {\"logo_url\", \"team_name\"}, {\"teams.logo_url\", \"teams.team_name\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded teams\",{{\"teams.logo_url\", \"home_team_logo_url\"}, {\"teams.team_name\", \"home_team\"}}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Renamed Columns\", {\"away_team_id\"}, teams, {\"team_id\"}, \"teams\", JoinKind.LeftOuter),",
                "    #\"Expanded teams1\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"teams\", {\"logo_url\", \"team_name\"}, {\"teams.logo_url\", \"teams.team_name\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded teams1\",{{\"teams.logo_url\", \"away_team_logo_url\"}, {\"teams.team_name\", \"away_team\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "lineups",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "fixture_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "edd3ada9-448a-4ae4-a28a-4eae11f10998",
            "sourceColumn": "fixture_id",
            "summarizeBy": "sum"
          },
          {
            "name": "player_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e01a1f63-2a8a-4753-bca7-ff81005821ef",
            "sourceColumn": "player_id",
            "summarizeBy": "sum"
          },
          {
            "name": "player_position",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ed7c62d-9f59-4add-a63b-aecfd100791d",
            "sourceColumn": "player_position",
            "summarizeBy": "none"
          },
          {
            "name": "startXI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "0e17252f-54c1-4a1d-8529-b7110d548512",
            "sourceColumn": "startXI",
            "summarizeBy": "none"
          },
          {
            "name": "team_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2a1c761d-9637-4a54-a6f6-2013eddc8a7e",
            "sourceColumn": "team_id",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "5f7a30ad-e07f-4ce8-b8e4-40d2f5cd6f35",
        "partitions": [
          {
            "name": "lineups-0c245804-3746-4723-a18e-03943b34a83c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(\"adb-6574875493875899.19.azuredatabricks.net\", \"sql/protocolv1/o/6574875493875899/0607-092353-qlk3ujuf\", [Catalog=null, Database=\"silver\", EnableAutomaticProxyDiscovery=null]),",
                "    lineups_silver_hive_metastore = Source{[Item=\"lineups\",Schema=\"silver\",Catalog=\"hive_metastore\"]}[Data]",
                "in",
                "    lineups_silver_hive_metastore"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "player_stats",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "assists",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "31299d98-6436-4fd0-8525-bee1b8c6ece0",
            "sourceColumn": "assists",
            "summarizeBy": "sum"
          },
          {
            "name": "conceded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f012ae99-1b7a-4af1-8723-6e707b41af48",
            "sourceColumn": "conceded",
            "summarizeBy": "sum"
          },
          {
            "name": "dribbles",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbffa88f-0ed2-4afa-bc98-c1ee10e29943",
            "sourceColumn": "dribbles",
            "summarizeBy": "none"
          },
          {
            "name": "duels",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "137837ed-c018-4323-b3ba-b98a741ebc02",
            "sourceColumn": "duels",
            "summarizeBy": "none"
          },
          {
            "name": "fixture_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ce0a5164-282d-4af9-8ad5-d74e859b57f9",
            "sourceColumn": "fixture_id",
            "summarizeBy": "sum"
          },
          {
            "name": "fouls",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6012b56c-6695-4d16-bf21-542f67959c43",
            "sourceColumn": "fouls",
            "summarizeBy": "none"
          },
          {
            "name": "goals_scored",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dd349a16-37bd-4624-8af0-c1d3bc55296c",
            "sourceColumn": "goals_scored",
            "summarizeBy": "sum"
          },
          {
            "name": "minutes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c78882df-fadf-452c-b6e6-a0f214772f25",
            "sourceColumn": "minutes",
            "summarizeBy": "sum"
          },
          {
            "name": "offsides",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "98c1e11c-72af-45db-a533-7ee3b7025f34",
            "sourceColumn": "offsides",
            "summarizeBy": "sum"
          },
          {
            "name": "passes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98e5e6c5-26dd-4625-9414-f48fda20b632",
            "sourceColumn": "passes",
            "summarizeBy": "none"
          },
          {
            "name": "penalty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba1592b2-4dc2-4a2b-8bea-db12fe33a90e",
            "sourceColumn": "penalty",
            "summarizeBy": "none"
          },
          {
            "name": "player_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f6e2c3f8-e811-4bf9-9694-3a5d3e45d6b3",
            "sourceColumn": "player_id",
            "summarizeBy": "sum"
          },
          {
            "name": "player_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55056c3f-200a-48ac-8901-eb63b12f622a",
            "sourceColumn": "player_name",
            "summarizeBy": "none"
          },
          {
            "name": "player_photo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1b8b45b-daf2-4477-b197-a4584057987a",
            "sourceColumn": "player_photo",
            "summarizeBy": "none"
          },
          {
            "name": "rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bdc8ffdf-715c-4b4f-9e95-d8b31624703e",
            "sourceColumn": "rating",
            "summarizeBy": "sum"
          },
          {
            "name": "red_cards",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb3b20ab-a04a-41e0-b630-632f2218883f",
            "sourceColumn": "red_cards",
            "summarizeBy": "sum"
          },
          {
            "name": "saves",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "39082533-ff75-4beb-8677-23c131f4d647",
            "sourceColumn": "saves",
            "summarizeBy": "sum"
          },
          {
            "name": "shots_on_target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "73c2bc20-bce6-4676-9ed4-c0d70f10a1d9",
            "sourceColumn": "shots_on_target",
            "summarizeBy": "sum"
          },
          {
            "name": "shots_total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9add5a4b-c80a-4cf0-a7ee-63391d689fbf",
            "sourceColumn": "shots_total",
            "summarizeBy": "sum"
          },
          {
            "name": "substitute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "9c8c3387-e14c-4df9-b3f8-682d2d38ef62",
            "sourceColumn": "substitute",
            "summarizeBy": "none"
          },
          {
            "name": "tackles",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef569baf-ad84-4686-b83b-93141b142cf7",
            "sourceColumn": "tackles",
            "summarizeBy": "none"
          },
          {
            "name": "team_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "44bdec17-6abd-43da-a2b2-8fba989328e4",
            "sourceColumn": "team_id",
            "summarizeBy": "sum"
          },
          {
            "name": "yellow_cards",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ed804b13-7b75-494a-90cf-501b30613639",
            "sourceColumn": "yellow_cards",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "edf0c766-c931-472e-8a28-f392c31a9965",
        "partitions": [
          {
            "name": "player_stats-6a7b7a32-111f-4052-b631-bb2b84b0b874",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(\"adb-6574875493875899.19.azuredatabricks.net\", \"sql/protocolv1/o/6574875493875899/0607-092353-qlk3ujuf\", [Catalog=null, Database=\"silver\", EnableAutomaticProxyDiscovery=null]),",
                "    player_stats_silver_hive_metastore = Source{[Item=\"player_stats\",Schema=\"silver\",Catalog=\"hive_metastore\"]}[Data]",
                "in",
                "    player_stats_silver_hive_metastore"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "players",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "birth_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e70dcc50-f5ce-4081-89f9-5aa070ad5b6c",
            "sourceColumn": "birth_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a861fe3f-b93f-449f-ab4f-86203259d8f4"
                },
                "isDefault": true,
                "relationship": "b3394e09-0de3-47e6-927c-239202816284"
              }
            ]
          },
          {
            "name": "height_cm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e72e611f-2462-4b9f-8284-2989233dc5e0",
            "sourceColumn": "height_cm",
            "summarizeBy": "none"
          },
          {
            "name": "nationality",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb596927-5509-470b-a088-67d7e9566ee1",
            "sourceColumn": "nationality",
            "summarizeBy": "none"
          },
          {
            "name": "photo_url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02ef5826-dba6-44c0-b7e4-35e21b839d84",
            "sourceColumn": "photo_url",
            "summarizeBy": "none"
          },
          {
            "name": "player_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "02f62093-cdb5-49e7-ae8a-4a91718b5823",
            "sourceColumn": "player_id",
            "summarizeBy": "none"
          },
          {
            "name": "player_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1376c8d4-4acb-4721-be29-17eb63462986",
            "sourceColumn": "player_name",
            "summarizeBy": "none"
          },
          {
            "name": "weight_kg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e27b9876-de68-482d-beec-c51be7d6be44",
            "sourceColumn": "weight_kg",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7dd22687-34a0-4436-92fc-17d61949131e",
        "partitions": [
          {
            "name": "players-f7cb4dec-cb3e-407a-84e2-89788ce1bfa1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(\"adb-6574875493875899.19.azuredatabricks.net\", \"sql/protocolv1/o/6574875493875899/0607-092353-qlk3ujuf\", [Catalog=null, Database=\"silver\", EnableAutomaticProxyDiscovery=null]),",
                "    players_silver_hive_metastore = Source{[Item=\"players\",Schema=\"silver\",Catalog=\"hive_metastore\"]}[Data],",
                "    #\"Removed Duplicates\" = Table.Distinct(players_silver_hive_metastore, {\"player_id\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "teams",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "logo_url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "01238047-49a0-49e1-b729-929c5fb0b933",
            "sourceColumn": "logo_url",
            "summarizeBy": "none"
          },
          {
            "name": "team_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c2435774-6479-4dc7-ba64-30f997e841b6",
            "sourceColumn": "team_id",
            "summarizeBy": "none"
          },
          {
            "name": "team_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63e8b489-7465-4cec-9e4f-caa444335040",
            "sourceColumn": "team_name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1b2b6bf7-8208-4106-b0c0-94440f331b44",
        "partitions": [
          {
            "name": "teams-d7a8681d-0eb8-4abf-9981-b93360d6e035",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(\"adb-6574875493875899.19.azuredatabricks.net\", \"sql/protocolv1/o/6574875493875899/0607-092353-qlk3ujuf\", [Catalog=null, Database=\"silver\", EnableAutomaticProxyDiscovery=null]),",
                "    teams_silver_hive_metastore = Source{[Item=\"teams\",Schema=\"silver\",Catalog=\"hive_metastore\"]}[Data]",
                "in",
                "    teams_silver_hive_metastore"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}